/*
 * This file is generated by jOOQ.
*/
package org.robertux.data.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.robertux.data.jooq.tables.Category;
import org.robertux.data.jooq.tables.SqliteSequence;
import org.robertux.data.jooq.tables.Task;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends SchemaImpl {

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();
    private static final long serialVersionUID = 1825577314;
    /**
     * The table <code>Category</code>.
     */
    public final Category CATEGORY = org.robertux.data.jooq.tables.Category.CATEGORY;

    /**
     * The table <code>Task</code>.
     */
    public final Task TASK = org.robertux.data.jooq.tables.Task.TASK;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = org.robertux.data.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Category.CATEGORY,
                Task.TASK,
                SqliteSequence.SQLITE_SEQUENCE);
    }
}
