/*
 * This file is generated by jOOQ.
*/
package org.robertux.data.jooq;


import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.robertux.data.jooq.tables.Category;
import org.robertux.data.jooq.tables.Task;
import org.robertux.data.jooq.tables.records.CategoryRecord;
import org.robertux.data.jooq.tables.records.TaskRecord;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code></code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> PK_CATEGORY = UniqueKeys0.PK_CATEGORY;
    public static final UniqueKey<TaskRecord> PK_TASK = UniqueKeys0.PK_TASK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoryRecord> PK_CATEGORY = createUniqueKey(Category.CATEGORY, "pk_Category", Category.CATEGORY.ID);
        public static final UniqueKey<TaskRecord> PK_TASK = createUniqueKey(Task.TASK, "pk_Task", Task.TASK.ID);
    }
}
