/*
 * This file is generated by jOOQ.
*/
package org.robertux.data.jooq;


import org.robertux.data.jooq.tables.Category;
import org.robertux.data.jooq.tables.SqliteSequence;
import org.robertux.data.jooq.tables.Task;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>Category</code>.
     */
    public static final Category CATEGORY = org.robertux.data.jooq.tables.Category.CATEGORY;

    /**
     * The table <code>Task</code>.
     */
    public static final Task TASK = org.robertux.data.jooq.tables.Task.TASK;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = org.robertux.data.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
